apiVersion: v1
kind: Service
metadata:
  name: pacman-service
  labels:
    app: pacman
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pacman
  type: LoadBalancer
